# Makefile generated by makegen 0.7
CC = gcc
LIBS = -lpcre 
FLAGS = 
DEFINE = -DOVECCOUNT=30 
OUTPUT = mvre

all: mvre

mvre: replace.o mvre.o 
	$(CC) $(FLAGS) $(LIBS) -o $(OUTPUT) replace.o mvre.o 

replace.o: replace.c
	$(CC) -c $(FLAGS) $(DEFINE) -o replace.o replace.c

mvre.o: mvre.c
	$(CC) -c $(FLAGS) $(DEFINE) -o mvre.o mvre.c

clean:
	rm *.o
	rm mvre
